name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build Docusaurus
        run: |
          npm install
          npm run build

      - name: Deploy Docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          clean: true