name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install & build React site
        run: |
          npm install
          npm run build

      - name: Install & build Docusaurus
        run: |
          npm install
          npm run build
        working-directory: docs

      - name: Deploy React site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          clean: false

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build
          target-folder: docs
          clean: false